# Write your MySQL query statement below
SELECT E1.EMPLOYEE_ID FROM EMPLOYEES E1 LEFT JOIN EMPLOYEES E2 ON E2.EMPLOYEE_ID=E1.MANAGER_ID
WHERE E2.EMPLOYEE_ID IS NULL AND E1.SALARY<30000 AND E1.MANAGER_ID IS NOT NULL ORDER BY E1.EMPLOYEE_ID;