# Write your MySQL query statement below
SELECT ST.STUDENT_ID,ST.STUDENT_NAME,S.SUBJECT_NAME,COUNT(E.SUBJECT_NAME) AS ATTENDED_EXAMS FROM STUDENTS ST CROSS JOIN SUBJECTS S 
LEFT JOIN EXAMINATIONS E ON ST.STUDENT_ID=E.STUDENT_ID AND S.SUBJECT_NAME=E.SUBJECT_NAME
GROUP BY ST.STUDENT_ID,S.SUBJECT_NAME
ORDER BY ST.STUDENT_ID,S.SUBJECT_NAME;