# Write your MySQL query statement below
SELECT ROUND(COUNT(A2.PLAYER_ID)/COUNT(A1.PLAYER_ID),2) AS FRACTION 
FROM ACTIVITY A1 LEFT OUTER JOIN ACTIVITY A2 ON A1.PLAYER_ID=A2.PLAYER_ID 
AND DATEDIFF(A2.EVENT_DATE,A1.EVENT_DATE)=1  
WHERE (A1.PLAYER_ID,A1.EVENT_DATE) IN(SELECT PLAYER_ID,MIN(EVENT_DATE) FROM ACTIVITY GROUP BY PLAYER_ID);