# Write your MySQL query statement below
SELECT PRODUCT_ID,NEW_PRICE AS PRICE FROM PRODUCTS WHERE (PRODUCT_ID,CHANGE_DATE) IN(SELECT PRODUCT_ID,MAX(CHANGE_DATE) FROM PRODUCTS WHERE CHANGE_DATE<="2019-08-16" GROUP BY PRODUCT_ID)
UNION
SELECT PRODUCT_ID,10 AS PRICE FROM PRODUCTS WHERE PRODUCT_ID NOT IN(SELECT PRODUCT_ID FROM PRODUCTS WHERE CHANGE_DATE<="2019-08-16");