# Write your MySQL query statement below
(
SELECT U.NAME AS RESULTS FROM MOVIERATING MR  JOIN USERS U ON MR.USER_ID=U.USER_ID GROUP BY U.NAME ORDER BY COUNT(*) DESC,U.NAME ASC LIMIT 1
)
UNION ALL
(
 SELECT M.TITLE AS RESULTS FROM MOVIERATING MR  JOIN MOVIES M ON M.MOVIE_ID=MR.MOVIE_ID 
 WHERE MR.CREATED_AT BETWEEN '2020-02-01' AND '2020-02-29' GROUP BY M.TITLE ORDER BY AVG(MR.RATING) DESC, M.TITLE ASC LIMIT 1
);