# Write your MySQL query statement below
SELECT QUEUE1.PERSON_NAME FROM QUEUE QUEUE1 JOIN QUEUE QUEUE2 ON QUEUE1.TURN>=QUEUE2.TURN 
GROUP BY QUEUE1.TURN HAVING SUM(QUEUE2.WEIGHT)<=1000 ORDER BY SUM(QUEUE2.WEIGHT) DESC LIMIT 1;